language: rust
rust: beta

before_install:
  - mkdir -pv ~/.local/bin
  - curl -LSfs https://japaric.github.io/trust/install.sh |
    sh -s --
    --git rust-lang-nursery/mdBook
    --crate mdbook
    --force
    --target x86_64-unknown-linux-gnu
    --tag v0.3.5
    --to ~/.local/bin

script:
  - ~/.local/bin/mdbook build
  - ~/.local/bin/mdbook test
  - cargo test --all

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local-dir: book
  keep-history: false
  on:
    branch: master
