[package]
name = "CLAiR-testing"
version = "0.1.0"
authors = ["Pascal Hertleif <killercup@gmail.com>"]
edition = "2018"

# Make tests work with the name used in the tutorial
[[bin]]
name = "grrs"
path = "src/main.rs"

[dependencies]
structopt = "0.3.22"
anyhow = "1.0"

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"
tempfile = "3"
